"""Add Loan model

Revision ID: 6f4a8f4c9e35
Revises: 1b7f083fba40
Create Date: 2025-06-02 23:32:27.334608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4a8f4c9e35'
down_revision: Union[str, None] = '1b7f083fba40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan', '')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    pass
    # ### end Alembic commands ###
